from upf.core.events import BaseEvent
from upf.core.event_types import EventType
from upf.core.event_payloads import SensorCuePayload, RFCuePayload

class RFCueAdapter:
    @property
    def supported_event_types(self):
        return [EventType.RF_CUE]
    
    def __init__(self, default_label: str = "drone", sensor_type: str = "rf", allowed_bandwidth_hz=(2.4e9, 5.8e9), bandwidth_tolerance_hz=0.2e9): # you can customize the default label and sensor type for the adapted cues
        self.default_label = default_label # e.g. "drone", "fire", "smoke"
        self.sensor_type = sensor_type # e.g. "camera", "rf", "thermal"
        self.allowed_bandwidth_hz = allowed_bandwidth_hz # tuple of (min_bandwidth_hz, max_bandwidth_hz) to filter RF cues by bandwidth
        self.bandwidth_tolerance_hz = bandwidth_tolerance_hz # tolerance in Hz for matching RF cues to the allowed bandwidth range

    async def process(self, event, bus):
        rf: RFCuePayload = event.payload # we know this is an RFCuePayload because this adapter only supports EventType.RF_CUE

        if not any(abs(rf.band_hz - b) <= self.bandwidth_tolerance_hz for b in self.allowed_bandwidth_hz): # filter out RF cues that don't match the allowed bandwidth range within the specified tolerance
            return # if the RF cue's bandwidth doesn't match, we skip processing it

        cue = SensorCuePayload( # adapt RF cue to generic sensor cue format
            label=self.default_label, # use the default label for RF cues (e.g. "drone")
            sensor_type=self.sensor_type, # pass through the
            confidence=float(rf.confidence), # ensure confidence is a float
            rf=rf, # include the full RF cue details in the adapted cue for downstream processors that may want to use it
        )

        cue_event = BaseEvent.create( # create a new event with the adapted cue payload
            event_type=EventType.SENSOR_CUE, # set the event type to SENSOR_CUE
            source_id="rf_cue_adapter", # use a distinct source_id to indicate this event was generated by the adapter
            payload=cue, # use the adapted cue as the payload
            correlation_id=event.event_id # correlate this new event with the original RF cue event
        )

        await bus.publish(cue_event) # publish the adapted cue event to the bus