import time
from collections import deque
from typing import Optional

from upf.core.event_types import EventType
from upf.core.events import BaseEvent
from upf.core.event_payloads import FusionReadyPayload, RFCuePayload

class RFFusionProcessor:
    @property
    def supported_event_types(self):
        return [EventType.RF_CUE, EventType.FUSION_READY_ALERT]
    
    def __init__(
            self,
            window_seconds: float = 2.0, # how long to keep recent RF cues for fusion
            min_rf_confidence: float = 0.55, # minimum confidence of RF cues to be considered for fusion
            boost_weight: float = 0.25, # boost = rf_confidence * boost_weight, e.g. 0.25 means a 0.8 confidence RF cue would boost the alert confidence by 0.2 (0.8 * 0.25)
            high_threshold: float = 0.85 # if boosted confidence exceeds this threshold, the alert is considered high priority
    ):
        self.window_seconds = window_seconds 
        self.min_rf_confidence = min_rf_confidence
        self.boost_weight = boost_weight
        self.high_threshold = high_threshold

        self.rf_cues = deque() # store recent RF cues as (timestamp, RFCuePayload) tuples

    async def process(self, event, bus): 
        now = time.time() # current timestamp in seconds

        if event.event_type == EventType.RF_CUE: # buffer RF cues for potential fusion with future alerts
            rf: RFCuePayload = event.payload 
            if rf.confidence >= self.min_rf_confidence: # only consider RF cues above the minimum confidence threshold
                self.rf_cues.append((now, rf)) # add new RF cue to the buffer

            while self.rf_cues and (now - self.rf_cues[0][0] > self.window_seconds): # remove RF cues that are older than the time window
                self.rf_cues.popleft() 
            return # no output event generated for RF cues, they are just buffered for future fusion
        
        if event.event_type != EventType.FUSION_READY_ALERT:
            return # ignore unsupported event types
        
        if event.source_id == "rf_fusion_processor": 
            return # avoid processing events generated by this processor itself to prevent feedback loops
        
        fr: FusionReadyPayload = event.payload # the original alert that is ready for fusion

        scored = fr.original_alert # the original scored alert that is ready for fusion, contains the original alert and its confidence and severity
        base_alert = scored.original_alert # the original alert that was scored
        label = getattr(base_alert, "label", None) # try to get the label from the original alert, if it exists (e.g. for VisionAlertPayload), otherwise use None 

        if label != "drone": # only apply RF fusion to alerts that are related to drones, skip other types of alerts
            return
        
        if not self.rf_cues: # if there are no recent RF cues available, we cannot perform fusion, so we just return without modifying the alert
            return 
        
        _, rf = self.rf_cues[-1] # get the most recent RF cue from the buffer (timestamp is ignored since we already filtered out old cues)

        boost = rf.confidence * self.boost_weight # calculate the boost to the alert confidence based on the RF cue confidence and the configured boost weight
        boosted_confidence = min(1.0, fr.confidence + boost) # calculate the new boosted confidence for the alert, capped at 1.0

        boosted_severity = fr.severity.upper() # start with the original severity, but we may upgrade it to HIGH if the boosted confidence exceeds the high threshold
        if boosted_confidence >= self.high_threshold: # if the boosted confidence exceeds the high threshold, we can consider this a high severity alert
            boosted_severity = "HIGH" # upgrade severity to HIGH if the boosted confidence exceeds the high threshold

        boosted_payload = FusionReadyPayload( # create a new FusionReadyPayload with the boosted confidence and severity, and include the RF cue and boost information for transparency
            original_alert=fr.original_alert, # keep the original alert information unchanged 
            confidence=round(boosted_confidence, 2), # round the boosted confidence to 2 decimal places for cleaner output
            severity=boosted_severity, # update the severity if the boosted confidence exceeds the high threshold
            rf_cue=rf, # include the RF cue information in the payload for transparency and potential use by downstream processors
            rf_boost=round(boost, 3), # include the calculated boost in the payload, rounded to 3 decimal places for cleaner output
        )

        boosted_event = BaseEvent.create( # create a new event with the boosted alert information
            event_type=EventType.FUSION_READY_ALERT, # the same event type since this is still a fusion-ready alert, just with updated
            source_id="rf_fusion_processor", # set the source_id to identify that this event was generated by the RF fusion processor, which can be useful for debugging and to prevent feedback loops
            payload=boosted_payload, # the new payload with the boosted confidence and severity
            correlation_id=event.event_id # keep the same correlation_id as the original event to maintain the traceability of the alert through the processing pipeline
        )

        await bus.publish(boosted_event)
