from upf.core.events import BaseEvent
from upf.core.event_types import EventType
from upf.core.event_payloads import ThermalCuePayload, SensorCuePayload

class ThermalCueAdapter:
    @property
    def supported_event_types(self):
        return [EventType.THERMAL_CUE]
    
    def __init__(self, default_label: str = "drone", sensor_type: str = "thermal"): # you can customize the default label and sensor type for the adapted cues
        self.default_label = default_label # e.g. "drone", "fire", "smoke"
        self.sensor_type = sensor_type # e.g. "camera", "rf", "thermal"

    async def process(self, event, bus): 
        th: ThermalCuePayload = event.payload # we know this is a ThermalCuePayload because this adapter only supports EventType.THERMAL_CUE
        
        cue = SensorCuePayload( # adapt thermal cue to generic sensor cue format
            label=self.default_label, # use the default label for all adapted cues
            sensor_type=self.sensor_type, # pass through the sensor type (e.g. "thermal")
            confidence=float(th.confidence), # ensure confidence is a float
            camera_id=th.camera_id, # pass through camera_id if available
            rf=None, # no RF details for thermal cues
            vision=None, # no vision details for thermal cues
            thermal=th # include the original thermal cue details in the adapted cue payload for reference
        )

        cue_event = BaseEvent.create( # create a new event with the adapted cue payload
            event_type=EventType.SENSOR_CUE, # set the event type to SENSOR_CUE
            source_id="thermal_cue_adapter", # use a distinct source_id to indicate this event was generated by the adapter
            payload=cue, # use the adapted cue as the payload
            correlation_id=event.event_id # correlate this new event with the original thermal cue event
        )

        await bus.publish(cue_event) # publish the adapted cue event to the bus