from upf.core.events import BaseEvent
from upf.core.event_types import EventType
from upf.core.event_payloads import SensorCuePayload, VisionAlertPayload

class VisionCueAdapter:
    @property
    def supported_event_types(self):
        return [EventType.VISION_ALERT]
    
    def __init__(self, sensor_type:str = "vision"):
        self.sensor_type = sensor_type # e.g. "camera", "rf", "thermal" - you can customize the sensor type for the adapted cues

    async def process(self, event, bus): 
        v: VisionAlertPayload = event.payload # we know this is a VisionAlertPayload because this adapter only supports EventType.VISION_ALERT
        
        cue = SensorCuePayload( # adapt vision alert to generic sensor cue format
            label=v.label, # use the label from the vision alert (e.g. "drone", "fire", "smoke")
            sensor_type=self.sensor_type, # pass through the sensor type (e.g. "camera")
            confidence=float(v.max_confidence), # use the max confidence from the vision alert as the confidence for the adapted cue
            camera_id=v.camera_id, # pass through camera_id if available
            vision=v # include the full vision alert details in the adapted cue for downstream processors that may want to use it
        )
        
        cue_event = BaseEvent.create( # create a new event with the adapted cue payload
            event_type=EventType.SENSOR_CUE, # set the event type to SENSOR_CUE
            source_id="vision_cue_adapter", # use a distinct source_id to indicate this event was generated by the adapter
            payload=cue, # use the adapted cue as the payload
            correlation_id=event.event_id # correlate this new event with the original vision alert event
        )
        await bus.publish(cue_event) # publish the adapted cue event to the bus
